# 基础站点配置
title: Jgjingsgo_OJ
description: "静态的在线测评系统"
url: "https://weupseanet.github.io"
baseurl: ""
repository: weupseanet/weupseanet.github.io

# 主题配置
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"

# 构建配置
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# 永久链接
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# 作者信息
author:
  name: "Jgjingsgo"
  avatar: "https://cravatar.cn/avatar/e7956356a5d3e33eb79167720a2b3498"
  bio: "国内"高质量"测评平台"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/weupseanet"

# 导航栏
header:
  main:
    - title: "首页"
      url: /
    - title: "所有题目"
      url: /posts/
    - title: "注册&使用"
      url: /about/

# 页脚配置
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/weupseanet"

# 搜索配置
search: true
search_provider: "lunr"
search_full_content: false

# 包含/排除文件
include:
  - _pages
exclude:
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-cache
  - .jekyll-metadata
  - vendor
  - Gemfile
  - Gemfile.lock
